name: Release Binaries

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    name: Build binaries for ${{ matrix.goos }} / ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64  # 跳过不常用组合

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'  # 根据你的项目选择 Go 版本

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          ext=""
          if [ "$GOOS" = "windows" ]; then ext=".exe"; fi
          go build -ldflags="-s -w" -o "jcli${ext}" .
          zip "dist/jcli-${GOOS}-${GOARCH}.zip" "jcli${ext}"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
